### ISSUE TITLE
Migrate project.openmandriva.org

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/OpenMandrivaLx#3]
Migrate project.openmandriva.org to waffle.io

**Comment by itchka** [comment]
Projects are worked under the issues inteface.

**Comment by itchka** [comment]
How to move items to the "Ready" column there's no drag'n drop

**Comment by tpgxyz** [comment]
d'n'd works here

**Comment by itchka** [comment]
Found it. Moved it back again so undo works ok.

**Comment by tpgxyz** [comment]
Closing as old
