### ISSUE TITLE
Switch to libjpeg-turbo

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/OpenMandrivaLx#36]
Maybe it is time to switch back from mozjpeg to libjpeg-turbo ?
In short words, these days better compression ratio is not an issue, but speed it, while libjpeg-turbo is like 4 times faster.

More explanations here:
https://libjpeg-turbo.org/About/Mozjpeg

**Comment by abucodonosor** [comment]
Yes, +1 from me for that.

**Comment by tpgxyz** [comment]
This is done.
